spring:
  security:
    basic:
      enabled: true
    user:
      name: butu
      password: 991218
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
